name: Build

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - run: pnpm install
    - run: pnpm run build

    - uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: build
